export const getIconName = amenity => {
    const iconMap = {
      Pool: 'pool',
      'Lockable': 'lock',
      'Hot tub': 'hot-tub',
      Rooftop: 'sunglasses',
      Gym: 'dumbbell',
      'Coffee machine': 'coffee-outline',
      'Dance Room': 'shoe-ballet',
      'Bed without mattress': 'bed-queen-outline',
      'Bed with mattress': 'bed-queen',
      Private: 'account',
      Shared: 'account-group',
      'Hot water': 'thermometer',
      'Dedicated workspace': 'desk',
      'Clothing storage: closet or dresser': 'wardrobe',
      Window: 'window-closed-variant',
      Dryer: 'tumble-dryer',
      Washer: 'washing-machine',
      TV: 'television',
      'Air condition': 'air-conditioner',
      Heating: 'fire',
      'Smoke detector': 'smoke-detector-variant',
      'Carbon monoxide alarm': 'smoke-detector',
      'Fire extinguisher': 'fire-extinguisher',
      Wifi: 'wifi',
      Electricity: 'lightning-bolt-outline',
      Gas: 'circle-outline',
      Water: 'water-outline',
      Trash: 'delete-outline',
      Refrigerator: 'fridge-outline',
      Microwave: 'microwave',
      Dishwasher: 'dishwasher',
      Stove: 'stove',
      'Parking on property': 'parking',
      'Parking off property': 'parking',
      Elevator: 'elevator',
      Stairs: 'stairs',
      'Ceiling fan': 'ceiling-fan',
      Oven: 'toaster-oven',
    };
    return iconMap[amenity] || 'circle-small'; // Return a default icon if no match is found
  };